apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kiko-data
  namespace: kiko
  labels:
    app.kubernetes.io/name: kiko
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 24Gi
