apiVersion: v1
kind: Service
metadata:
  name: kiko
  namespace: kiko
  labels:
    app.kubernetes.io/name: kiko
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kiko
  ports:
    - name: http
      port: 8080
      targetPort: http
