{{- if and .Values.secrets.create (not .Values.secrets.existingSecret) .Values.secrets.dsn }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kiko.databaseSecretName" . }}
  labels:
    {{- include "kiko.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.secrets.secretKey }}: {{ .Values.secrets.dsn | quote }}
{{- end }}
